import type { GlobalThemeOverrides } from 'naive-ui'

/** Naive UI 主题：与 tokens.css 同一套色板与圆角 */
export const themeOverrides: GlobalThemeOverrides = {
  common: {
    primaryColor: '#2b7fff',
    primaryColorHover: '#4d93ff',
    primaryColorPressed: '#1f6fe6',
    primaryColorSuppl: '#2b7fff',
    successColor: '#16b364',
    successColorHover: '#22c96f',
    successColorPressed: '#12a057',
    warningColor: '#f59e0b',
    errorColor: '#ef4444',
    errorColorHover: '#f26262',
    errorColorPressed: '#dc2626',
    infoColor: '#2b7fff',
    borderRadius: '8px',
    borderRadiusSmall: '6px',
    fontFamily: 'var(--font)',
    fontSize: '14px',
    fontSizeMedium: '14px',
    fontSizeSmall: '13px',
    textColorBase: '#1f2329',
    textColor1: '#1f2329',
    textColor2: '#4e5969',
    textColor3: '#86909c',
    borderColor: '#e5e6eb',
    dividerColor: '#eff0f2',
    hoverColor: '#f5f7fa',
    bodyColor: '#f4f5f7',
    cardColor: '#ffffff',
    modalColor: '#ffffff',
    popoverColor: '#ffffff',
    boxShadow2: '0 10px 32px rgba(31, 35, 41, 0.14)',
  },
  Card: { borderRadius: '14px', paddingMedium: '18px 20px', titleFontSizeMedium: '15px' },
  Button: { borderRadiusMedium: '8px', borderRadiusSmall: '7px', fontWeight: '500' },
  Input: { borderRadius: '8px' },
  Tag: { borderRadius: '6px' },
  Dialog: { borderRadius: '14px', padding: '22px 24px' },
  Modal: { boxShadow: '0 20px 60px rgba(31, 35, 41, 0.18)' },
  Dropdown: { borderRadius: '10px', optionHeightMedium: '34px' },
  Popover: { borderRadius: '10px' },
  DataTable: { borderRadius: '12px', thFontWeight: '600' },
  Tabs: { tabBorderRadius: '7px' },
  Message: { borderRadius: '10px' },
}
